console.log('LightsidE')
console.log('JavaScriot')
document.write('LightsidE')
// alert('pop up')
// prompt('what is yout name')
console.log('I\'m')
console.log("precious")
console.log(`hi, my name`)
console.log(typeof('LIGHTSIDE'))
console.log(typeof(5.5))
console.log(11.5)
console.log(true)
console.log(null)
console.log(typeof(null))
console.log(2.5 + 1.75)
console.log('my name is ' + 'Precious')
console.log('my name is' - ' precious')
console.log(2**3)
console.log(3%2)
console.log(5%2)
console.log(2%5)
console.log(3+1*2)
console.log(true&&true)
console.log(true&&false)
console.log(false&&true)
console.log(false&&false)
console.log(true||true)
// console.log(!!true)